name:                haskell-university-solutions
version:             0.1.0.0
github:              "alem0lars/haskell-university-solutions"
license:             BSD3
author:              "Alessandro Molari"
maintainer:          "molari.alessandro@gmail.com"
copyright:           "Copyright (c) 2016-2017 Alessandro Molari"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/alem0lars/haskell-university-solutions#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-university-solutions-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-university-solutions

tests:
  haskell-university-solutions-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-university-solutions
